### ISSUE TITLE
Bluetooth Connection Issues for Swarm

### ISSUE THREAD

**Issue by anaammostafiz** [antonellabarisic/sphero_sprk_ros#1]
I am trying to run a Sphero SPRK+ swarm using this driver, however I am having a few problems when running drivers.launch. It is random which Spheros will connect and refuse to connect on any given run. Also, sometimes a Sphero will connect but then immediately disconnect. Distance is not the source of these problems as my computer is right next to the Spheros.

Then, after connecting, I cannot reliably send cmd_vel messages to more than one Sphero at a time. The Spheros will either stutter or not move at all, although I am publishing to their respective topics. 

My questions are: 
@antonellabarisic Can I do anything to resolve the connection issues?
@mkrizmancic In your experience developing a Sphero SPRK+ swarm, did you face similar issues? If so, how did you resolve them?

Thank you so much for your help; I realize these are old repositories and robots, but it would be really cool if I could get this to work.

-------------------------------------------------------------------------------------------------  

Here are my specs:
Dell Latitude E6430
Ubuntu 18.04
*Linux Kernel 5.4.0-150 
ROS Melodic
Python 2.7
Bluetooth 5.1 from the ASUS BT500 USB Adapter

*I realize that this kernel has not been verified yet, but if I switch to 5.0.0-29 or 5.4.0-48, my wifi and bluetooth stop working.

**Comment by mkrizmancic** [comment]
Hello, thank you for reporting the issue. We have received several reports of similar problems and have experienced them ourselves. Although we are not certain of the cause, it is likely related to changes in the Linux kernel, Bluetooth drivers, and/or Python Bluetooth packages.

About four years ago, when this package was created, we occasionally encountered difficulties when connecting to multiple Spheros. However, once the connection was established, it was smooth and reliable. Problems similar to what you are describing began to appear about a year ago, and we have not made any significant changes to the driver other than some minor formatting.

Unfortunately, we do not have a solution for this issue at the moment. However, we recommend that you try our new [Sphero driver](https://github.com/larics/sphero_robot/tree/master/sphero_driver_v2), which is based on [this awesome package](https://github.com/artificial-intelligence-class/spherov2.py).
